USER_CREDENTIALS = {
    "sky_octopus": "tentaclesInTheWind123",
    "cloud_squid": "soaringTentacleDreams!",
    "winged_kraken": "flapYourArmsAndFly22",
    "aero_cephalopod": "jetsAndInkTrails77",
    "tentacle_flyer": "eightArmsInTheSky99",
    "ink_cloud_rider": "floatingThroughInkStorms",
    "storm_octopus": "thunderTentacles@Sky",
    "soaring_squid": "aboveTheOceanSpray88",
    "wingtip_kraken": "airborneArmsForever!",
    "jetstream_octopus": "glidingOverWaves*22",
    "octo_pilot": "aviatorOfTheSeaAndSky",
    "cloud_inkling": "octopusInTheStratosphere",
    "cephalopod_flier": "tentaclePowerTakesFlight",
    "ink_aviator": "trailingBlackClouds22",
    "skyward_squid": "cephalopodsReachNewHeights",
    "flying_kraken": "beastOfAirAndSea007",
    "hover_octopus": "tentaclesHoverAboveLand",
    "stormy_cephalopod": "blownByWindAndWaves88",
    "aerial_squid": "dancingWithCloudsAndSpray",
    "glider_octopus": "soaringWithSilentGrace!"
}
